trigger: none

variables:
  SERVICE_CONNECTION: 'cbie-rg'
  CONTAINER_REGISTRY_CONNECTION: 'cbiecontainerregistry'
  CONTAINER_REGISTRY_URL: 'cbiecontainerregistry.azurecr.io'
  RESOURCE_GROUP: 'cbie-rg'
  IMAGE_NAME: 'doccano'
  TAG: '$(Build.BuildId)'
  APP_SERVICE: 'cbie-doccano-backend'

pool:
  name: 'Default'

steps:
  - task: Docker@2
    displayName: Build and push an image to container registry
    continueOnError: true
    inputs:
      command: buildAndPush
      repository: '$(IMAGE_NAME)'
      dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile.prod'
      buildContext: '$(Build.SourcesDirectory)'
      containerRegistry: $(CONTAINER_REGISTRY_CONNECTION)
      tags: $(TAG),latest

  - task: AzureWebAppContainer@1
    inputs:
      azureSubscription: '$(RESOURCE_GROUP)'
      appName: 'cbie-doccano-backend'
      deployToSlotOrASE: true
      resourceGroupName: '$(RESOURCE_GROUP)'
      multicontainerConfigFile: '$(Build.SourcesDirectory)/docker/docker-compose.app-service.yml'